import { Crop, WeatherAlert, FarmingTip } from './types';

export const crops: Crop[] = [
  {
    id: 'wheat-haryana-rabi',
    nameEnglish: 'Wheat',
    nameLocal: 'गेहूं',
    imageUrl: 'https://images.unsplash.com/photo-1514481043218-e965c5886f06?q=80&w=1080',
    supportedStateIds: ['haryana', 'punjab', 'uttar-pradesh'],
    suitableSeasonIds: ['rabi'],
    soilType: 'Loamy',
    idealTemperature: '15-25°C',
    idealRainfall: '50-90 cm',
    expectedYield: 2000,
    approximateMarketPrice: 2125,
    isVisible: true,
  },
  {
    id: 'rice-westbengal-kharif',
    nameEnglish: 'Rice',
    nameLocal: 'चावल',
    imageUrl: 'https://images.unsplash.com/photo-1599328580087-15c9dab481f3?q=80&w=1080',
    supportedStateIds: ['west-bengal', 'punjab', 'andhra-pradesh'],
    suitableSeasonIds: ['kharif'],
    soilType: 'Clayey Loam',
    idealTemperature: '21-37°C',
    idealRainfall: '150-300 cm',
    expectedYield: 2500,
    approximateMarketPrice: 2040,
    isVisible: true,
  },
  {
    id: 'maize-karnataka-kharif',
    nameEnglish: 'Maize (Corn)',
    nameLocal: 'मक्का',
    imageUrl: 'https://images.unsplash.com/photo-1551810080-3eb3be72d3f4?q=80&w=1080',
    supportedStateIds: ['karnataka', 'maharashtra', 'rajasthan'],
    suitableSeasonIds: ['kharif'],
    soilType: 'Red Loam',
    idealTemperature: '21-27°C',
    idealRainfall: '50-100 cm',
    expectedYield: 3000,
    approximateMarketPrice: 1962,
    isVisible: true,
  },
  {
    id: 'sugarcane-maharashtra-annual',
    nameEnglish: 'Sugarcane',
    nameLocal: 'गन्ना',
    imageUrl: 'https://images.unsplash.com/photo-1570295289045-885a6b13735b?q=80&w=1080',
    supportedStateIds: ['maharashtra', 'uttar-pradesh', 'karnataka'],
    suitableSeasonIds: ['kharif', 'rabi'], // Annual crop
    soilType: 'Heavy Loam',
    idealTemperature: '20-26°C',
    idealRainfall: '75-120 cm',
    expectedYield: 40000,
    approximateMarketPrice: 315,
    isVisible: true,
  },
  {
    id: 'cotton-gujarat-kharif',
    nameEnglish: 'Cotton',
    nameLocal: 'कपास',
    imageUrl: 'https://images.unsplash.com/photo-1633527992904-53f86f81a23a?q=80&w=1080',
    supportedStateIds: ['gujarat', 'maharashtra', 'telangana'],
    suitableSeasonIds: ['kharif'],
    soilType: 'Black Cotton Soil',
    idealTemperature: '21-30°C',
    idealRainfall: '50-100 cm',
    expectedYield: 500,
    approximateMarketPrice: 6025,
    isVisible: false,
  },
];

export const weatherAlerts: WeatherAlert[] = [
  {
    id: 'heavy-rain-warning',
    thresholdRain: 50,
    thresholdTemperatureMin: 0,
    thresholdTemperatureMax: 50,
    frostRisk: false,
    alertMessage: 'Heavy rainfall expected. Postpone irrigation and protect young seedlings.',
    recommendedActions: 'Delay irrigation, ensure proper drainage.',
    isEnabled: true,
  },
  {
    id: 'heatwave-alert',
    thresholdRain: 100,
    thresholdTemperatureMin: 0,
    thresholdTemperatureMax: 40,
    frostRisk: false,
    alertMessage: 'Heatwave conditions approaching. Ensure adequate irrigation to prevent crop stress.',
    recommendedActions: 'Increase irrigation frequency, apply mulch.',
    isEnabled: true,
  },
  {
    id: 'frost-risk-alert',
    thresholdRain: 100,
    thresholdTemperatureMin: 4,
    thresholdTemperatureMax: 50,
    frostRisk: true,
    alertMessage: 'Frost risk overnight. Protect sensitive crops.',
    recommendedActions: 'Cover crops, use sprinklers to raise temperature.',
    isEnabled: true,
  },
  {
    id: 'moderate-rain-forecast',
    thresholdRain: 20,
    thresholdTemperatureMin: 0,
    thresholdTemperatureMax: 50,
    frostRisk: false,
    alertMessage: 'Moderate rain expected. Plan pesticide spraying accordingly.',
    recommendedActions: 'Avoid spraying pesticides 24 hours before rain.',
    isEnabled: true,
  },
  {
    id: 'high-humidity-warning',
    thresholdRain: 100,
    thresholdTemperatureMin: 0,
    thresholdTemperatureMax: 50,
    frostRisk: false,
    alertMessage: 'High humidity increases risk of fungal diseases.',
    recommendedActions: 'Monitor crops for fungal infections, ensure good air circulation.',
    isEnabled: false,
  },
];

export const farmingTips: FarmingTip[] = [
  {
    id: 'soil-testing-tip',
    tipText: 'Start the season right! Test your soil to understand nutrient needs and pH levels for better crop performance.',
    language: 'en',
    scheduledDate: new Date().toISOString(),
    isEnabled: true,
  },
  {
    id: 'crop-rotation-tip',
    tipText: 'Practice crop rotation to improve soil health, reduce pests, and increase yields. Avoid planting the same family of crops in the same field year after year.',
    language: 'en',
    scheduledDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    isEnabled: true,
  },
  {
    id: 'water-conservation-tip',
    tipText: 'Use drip irrigation or sprinklers to conserve water and deliver it directly to the crop roots, minimizing evaporation.',
    language: 'en',
    scheduledDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    isEnabled: true,
  },
  {
    id: 'ipm-tip',
    tipText: 'Adopt Integrated Pest Management (IPM). Use beneficial insects, traps, and resistant varieties before resorting to chemical pesticides.',
    language: 'en',
    scheduledDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    isEnabled: true,
  },
  {
    id: 'harvesting-tip',
    tipText: 'Harvest your crops at the right time to ensure maximum quality and market value. Check for visual cues of readiness.',
    language: 'en',
    scheduledDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    isEnabled: false,
  },
];
