import { Crop, WeatherAlert, FarmingTip, CropLifecycle } from './types';

export const crops: Crop[] = [
  {
    id: 'wheat-haryana-rabi',
    nameEnglish: 'Wheat',
    nameLocal: 'गेहूं',
    imageUrl: 'https://images.unsplash.com/photo-1514481043218-e965c5886f06?q=80&w=1080',
    supportedStateIds: ['haryana', 'punjab', 'uttar-pradesh'],
    suitableSeasonIds: ['rabi'],
    soilType: 'Loamy',
    idealTemperature: '15-25°C',
    idealRainfall: '50-90 cm',
    expectedYield: 2000,
    approximateMarketPrice: 2125,
    isVisible: true,
  },
  {
    id: 'rice-westbengal-kharif',
    nameEnglish: 'Rice',
    nameLocal: 'चावल',
    imageUrl: 'https://images.unsplash.com/photo-1599328580087-15c9dab481f3?q=80&w=1080',
    supportedStateIds: ['west-bengal', 'punjab', 'andhra-pradesh'],
    suitableSeasonIds: ['kharif'],
    soilType: 'Clayey Loam',
    idealTemperature: '21-37°C',
    idealRainfall: '150-300 cm',
    expectedYield: 2500,
    approximateMarketPrice: 2040,
    isVisible: true,
  },
  {
    id: 'maize-karnataka-kharif',
    nameEnglish: 'Maize (Corn)',
    nameLocal: 'मक्का',
    imageUrl: 'https://images.unsplash.com/photo-1551810080-3eb3be72d3f4?q=80&w=1080',
    supportedStateIds: ['karnataka', 'maharashtra', 'rajasthan'],
    suitableSeasonIds: ['kharif'],
    soilType: 'Red Loam',
    idealTemperature: '21-27°C',
    idealRainfall: '50-100 cm',
    expectedYield: 3000,
    approximateMarketPrice: 1962,
    isVisible: true,
  },
  {
    id: 'sugarcane-maharashtra-annual',
    nameEnglish: 'Sugarcane',
    nameLocal: 'गन्ना',
    imageUrl: 'https://images.unsplash.com/photo-1570295289045-885a6b13735b?q=80&w=1080',
    supportedStateIds: ['maharashtra', 'uttar-pradesh', 'karnataka'],
    suitableSeasonIds: ['kharif', 'rabi'], // Annual crop
    soilType: 'Heavy Loam',
    idealTemperature: '20-26°C',
    idealRainfall: '75-120 cm',
    expectedYield: 40000,
    approximateMarketPrice: 315,
    isVisible: true,
  },
  {
    id: 'cotton-gujarat-kharif',
    nameEnglish: 'Cotton',
    nameLocal: 'कपास',
    imageUrl: 'https://images.unsplash.com/photo-1633527992904-53f86f81a23a?q=80&w=1080',
    supportedStateIds: ['gujarat', 'maharashtra', 'telangana'],
    suitableSeasonIds: ['kharif'],
    soilType: 'Black Cotton Soil',
    idealTemperature: '21-30°C',
    idealRainfall: '50-100 cm',
    expectedYield: 500,
    approximateMarketPrice: 6025,
    isVisible: true,
  },
];

export const weatherAlerts: WeatherAlert[] = [
  {
    id: 'heavy-rain-warning',
    thresholdRain: 50,
    thresholdTemperatureMin: 0,
    thresholdTemperatureMax: 50,
    frostRisk: false,
    alertMessage: 'Heavy rainfall expected. Postpone irrigation and protect young seedlings.',
    recommendedActions: 'Delay irrigation, ensure proper drainage.',
    isEnabled: true,
  },
  {
    id: 'heatwave-alert',
    thresholdRain: 100,
    thresholdTemperatureMin: 0,
    thresholdTemperatureMax: 40,
    frostRisk: false,
    alertMessage: 'Heatwave conditions approaching. Ensure adequate irrigation to prevent crop stress.',
    recommendedActions: 'Increase irrigation frequency, apply mulch.',
    isEnabled: true,
  },
  {
    id: 'frost-risk-alert',
    thresholdRain: 100,
    thresholdTemperatureMin: 4,
    thresholdTemperatureMax: 50,
    frostRisk: true,
    alertMessage: 'Frost risk overnight. Protect sensitive crops.',
    recommendedActions: 'Cover crops, use sprinklers to raise temperature.',
    isEnabled: true,
  },
  {
    id: 'moderate-rain-forecast',
    thresholdRain: 20,
    thresholdTemperatureMin: 0,
    thresholdTemperatureMax: 50,
    frostRisk: false,
    alertMessage: 'Moderate rain expected. Plan pesticide spraying accordingly.',
    recommendedActions: 'Avoid spraying pesticides 24 hours before rain.',
    isEnabled: true,
  },
  {
    id: 'high-humidity-warning',
    thresholdRain: 100,
    thresholdTemperatureMin: 0,
    thresholdTemperatureMax: 50,
    frostRisk: false,
    alertMessage: 'High humidity increases risk of fungal diseases.',
    recommendedActions: 'Monitor crops for fungal infections, ensure good air circulation.',
    isEnabled: false,
  },
];

export const farmingTips: FarmingTip[] = [
  {
    id: 'soil-testing-tip',
    tipText: 'Start the season right! Test your soil to understand nutrient needs and pH levels for better crop performance.',
    language: 'en',
    scheduledDate: new Date().toISOString(),
    isEnabled: true,
  },
  {
    id: 'crop-rotation-tip',
    tipText: 'Practice crop rotation to improve soil health, reduce pests, and increase yields. Avoid planting the same family of crops in the same field year after year.',
    language: 'en',
    scheduledDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    isEnabled: true,
  },
  {
    id: 'water-conservation-tip',
    tipText: 'Use drip irrigation or sprinklers to conserve water and deliver it directly to the crop roots, minimizing evaporation.',
    language: 'en',
    scheduledDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    isEnabled: true,
  },
  {
    id: 'ipm-tip',
    tipText: 'Adopt Integrated Pest Management (IPM). Use beneficial insects, traps, and resistant varieties before resorting to chemical pesticides.',
    language: 'en',
    scheduledDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    isEnabled: true,
  },
  {
    id: 'harvesting-tip',
    tipText: 'Harvest your crops at the right time to ensure maximum quality and market value. Check for visual cues of readiness.',
    language: 'en',
    scheduledDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    isEnabled: false,
  },
];

export const cropLifecycles: CropLifecycle[] = [
    {
        id: 'lc-wheat',
        cropId: 'wheat-haryana-rabi',
        sowingDateRange: 'Late October to mid-November',
        seedRate: '40-50 kg/acre',
        fertilizerBasalDose: 'DAP: 50kg, MOP: 20kg, Urea: 35kg per acre',
        fertilizerTopDressing: 'Urea: 50kg per acre after 25-30 days and at flowering',
        diseasePesticideGuide: 'For Yellow Rust, spray Propiconazole. For Aphids, use Imidacloprid.',
        irrigationSchedule: 'Critical stages: Crown Root Initiation, Tillering, Flowering, and Grain Filling. About 5-6 irrigations needed.',
        harvestingWindow: 'Late March to April',
        harvestingReadinessSigns: 'Golden yellow stalks, hard and dry grains.'
    },
    {
        id: 'lc-rice',
        cropId: 'rice-westbengal-kharif',
        sowingDateRange: 'June to July for transplanting',
        seedRate: '6-8 kg/acre for transplanting',
        fertilizerBasalDose: 'SSP: 75kg, Urea: 30kg, MOP: 25kg per acre',
        fertilizerTopDressing: 'Urea: 35kg per acre in two splits, at tillering and panicle initiation',
        diseasePesticideGuide: 'For Blast, use Tricyclazole. For Stem Borer, apply Fipronil granules.',
        irrigationSchedule: 'Maintain 2-5 cm of standing water for most of the growth period. Stop irrigation 15 days before harvest.',
        harvestingWindow: 'October to December',
        harvestingReadinessSigns: '80-85% of grains on the panicle are straw-colored.'
    },
    {
        id: 'lc-maize',
        cropId: 'maize-karnataka-kharif',
        sowingDateRange: 'June to July',
        seedRate: '8-10 kg/acre',
        fertilizerBasalDose: 'DAP: 50kg, MOP: 30kg per acre at sowing',
        fertilizerTopDressing: 'Urea: 50-60kg per acre at knee-high stage and another 50-60kg at tasseling.',
        diseasePesticideGuide: 'For Fall Armyworm, use Emamectin Benzoate. For Leaf Blight, Mancozeb spray is effective.',
        irrigationSchedule: 'Requires irrigation at critical stages like tasseling and silking if there is a dry spell.',
        harvestingWindow: 'September to October',
        harvestingReadinessSigns: 'Husk turns brownish, and grains are hard and dry.'
    },
    {
        id: 'lc-sugarcane',
        cropId: 'sugarcane-maharashtra-annual',
        sowingDateRange: 'October-November (pre-seasonal) or January-February (suru)',
        seedRate: '30,000-40,000 setts (stem cuttings) per acre',
        fertilizerBasalDose: 'Heavy dose of Farm Yard Manure. Chemical: 100kg Urea, 200kg SSP, 60kg MOP per acre.',
        fertilizerTopDressing: 'Urea in multiple splits at 45, 90, and 120 days after planting.',
        diseasePesticideGuide: 'For Red Rot, use disease-free setts. For Early Shoot Borer, apply Chlorantraniliprole.',
        irrigationSchedule: 'Frequent irrigation required. Use furrow irrigation method. Water every 7-10 days in summer.',
        harvestingWindow: '12-18 months after planting, depending on variety',
        harvestingReadinessSigns: 'Leaves turn yellow and wither. Canes produce a metallic sound when tapped.'
    },
    {
        id: 'lc-cotton',
        cropId: 'cotton-gujarat-kharif',
        sowingDateRange: 'Late May to June',
        seedRate: '1-2 kg/acre for hybrid seeds',
        fertilizerBasalDose: 'Full dose of Phosphorus and Potash, and 1/3 of Nitrogen at sowing.',
        fertilizerTopDressing: 'Remaining Nitrogen in two splits, at squaring and flowering stages.',
        diseasePesticideGuide: 'For Pink Bollworm, use pheromone traps and timely sprays of specific insecticides. For Whitefly, use Acetamiprid.',
        irrigationSchedule: 'Irrigate at flowering and boll development stages. Avoid water stress.',
        harvestingWindow: 'October to January, in multiple pickings',
        harvestingReadinessSigns: 'Bolls are fully mature and have begun to crack open naturally.'
    }
];
