
import { Crop, WeatherAlert, FarmingTip, CropLifecycle, State, Season } from './types';
import { PlaceHolderImages } from './placeholder-images';

const imageMap = new Map(PlaceHolderImages.map(img => [img.id, img.imageUrl]));

const getImage = (id: string) => {
    return imageMap.get(id) || `https://placehold.co/600x400/CCCCCC/FFFFFF?text=${id.replace('-', '+')}`;
}

export const states: State[] = [
  { id: 'haryana', name: 'Haryana', climateZone: 'Subtropical' },
  { id: 'punjab', name: 'Punjab', climateZone: 'Subtropical' },
  { id: 'uttar-pradesh', name: 'Uttar Pradesh', climateZone: 'Subtropical' },
  { id: 'west-bengal', name: 'West Bengal', climateZone: 'Tropical' },
  { id: 'andhra-pradesh', name: 'Andhra Pradesh', climateZone: 'Tropical' },
  { id: 'karnataka', name: 'Karnataka', climateZone: 'Tropical' },
  { id: 'maharashtra', name: 'Maharashtra', climateZone: 'Tropical' },
  { id: 'rajasthan', name: 'Rajasthan', climateZone: 'Arid' },
  { id: 'gujarat', name: 'Gujarat', climateZone: 'Arid' },
  { id: 'telangana', name: 'Telangana', climateZone: 'Tropical' },
  { id: 'madhya-pradesh', name: 'Madhya Pradesh', climateZone: 'Subtropical'},
];

export const seasons: Season[] = [
  {
    id: 'kharif',
    name: 'Kharif',
    startDate: new Date(new Date().getFullYear(), 5, 1).toISOString(),
    endDate: new Date(new Date().getFullYear(), 9, 31).toISOString(),
  },
  {
    id: 'rabi',
    name: 'Rabi',
    startDate: new Date(new Date().getFullYear(), 10, 1).toISOString(),
    endDate: new Date(new Date().getFullYear() + 1, 2, 31).toISOString(),
  },
  {
    id: 'zaid',
    name: 'Zaid',
    startDate: new Date(new Date().getFullYear(), 3, 1).toISOString(),
    endDate: new Date(new Date().getFullYear(), 4, 31).toISOString(),
  },
];


export const crops: Crop[] = [
  {
    id: 'wheat-haryana-rabi',
    nameEnglish: 'Wheat',
    nameLocal: 'गेहूं',
    imageUrl: getImage('wheat'),
    supportedStateIds: ['haryana', 'punjab', 'uttar-pradesh'],
    suitableSeasonIds: ['rabi'],
    soilType: 'Loamy',
    idealTemperature: '15-25°C',
    idealRainfall: '50-90 cm',
    expectedYield: 2000,
    approximateMarketPrice: 2125,
    isVisible: true,
  },
  {
    id: 'rice-westbengal-kharif',
    nameEnglish: 'Rice',
    nameLocal: 'चावल',
    imageUrl: getImage('rice'),
    supportedStateIds: ['west-bengal', 'punjab', 'andhra-pradesh'],
    suitableSeasonIds: ['kharif'],
    soilType: 'Clayey Loam',
    idealTemperature: '21-37°C',
    idealRainfall: '150-300 cm',
    expectedYield: 2500,
    approximateMarketPrice: 2040,
    isVisible: true,
  },
  {
    id: 'maize-karnataka-kharif',
    nameEnglish: 'Maize (Corn)',
    nameLocal: 'मक्का',
    imageUrl: getImage('corn'),
    supportedStateIds: ['karnataka', 'maharashtra', 'rajasthan'],
    suitableSeasonIds: ['kharif'],
    soilType: 'Red Loam',
    idealTemperature: '21-27°C',
    idealRainfall: '50-100 cm',
    expectedYield: 3000,
    approximateMarketPrice: 1962,
    isVisible: true,
  },
  {
    id: 'sugarcane-maharashtra-annual',
    nameEnglish: 'Sugarcane',
    nameLocal: 'गन्ना',
    imageUrl: getImage('sugarcane'),
    supportedStateIds: ['maharashtra', 'uttar-pradesh', 'karnataka'],
    suitableSeasonIds: ['kharif', 'rabi'], // Annual crop
    soilType: 'Heavy Loam',
    idealTemperature: '20-26°C',
    idealRainfall: '75-120 cm',
    expectedYield: 40000,
    approximateMarketPrice: 315,
    isVisible: true,
  },
  {
    id: 'cotton-gujarat-kharif',
    nameEnglish: 'Cotton',
    nameLocal: 'कपास',
    imageUrl: getImage('cotton'),
    supportedStateIds: ['gujarat', 'maharashtra', 'telangana'],
    suitableSeasonIds: ['kharif'],
    soilType: 'Black Cotton Soil',
    idealTemperature: '21-30°C',
    idealRainfall: '50-100 cm',
    expectedYield: 500,
    approximateMarketPrice: 6025,
    isVisible: true,
  },
  {
    id: 'mustard-rajasthan-rabi',
    nameEnglish: 'Mustard',
    nameLocal: 'सरसों',
    imageUrl: getImage('mustard'),
    supportedStateIds: ['rajasthan', 'haryana', 'uttar-pradesh'],
    suitableSeasonIds: ['rabi'],
    soilType: 'Sandy Loam',
    idealTemperature: '10-25°C',
    idealRainfall: '35-50 cm',
    expectedYield: 800,
    approximateMarketPrice: 5450,
    isVisible: true,
  },
  {
    id: 'potato-uttarpradesh-rabi',
    nameEnglish: 'Potato',
    nameLocal: 'आलू',
    imageUrl: getImage('potato'),
    supportedStateIds: ['uttar-pradesh', 'west-bengal', 'punjab'],
    suitableSeasonIds: ['rabi'],
    soilType: 'Well-drained Sandy Loam',
    idealTemperature: '15-20°C',
    idealRainfall: '50-75 cm',
    expectedYield: 12000,
    approximateMarketPrice: 1500,
    isVisible: true,
  },
  {
    id: 'soybean-maharashtra-kharif',
    nameEnglish: 'Soybean',
    nameLocal: 'सोयाबीन',
    imageUrl: getImage('soybean'),
    supportedStateIds: ['maharashtra', 'madhya-pradesh'],
    suitableSeasonIds: ['kharif'],
    soilType: 'Clay Loam',
    idealTemperature: '20-30°C',
    idealRainfall: '60-75 cm',
    expectedYield: 1000,
    approximateMarketPrice: 4300,
    isVisible: true,
  },
  {
    id: 'groundnut-gujarat-kharif',
    nameEnglish: 'Groundnut',
    nameLocal: 'मूंगफली',
    imageUrl: getImage('groundnut'),
    supportedStateIds: ['gujarat', 'andhra-pradesh', 'karnataka'],
    suitableSeasonIds: ['kharif', 'rabi'],
    soilType: 'Sandy Loam',
    idealTemperature: '25-35°C',
    idealRainfall: '50-125 cm',
    expectedYield: 1200,
    approximateMarketPrice: 5850,
    isVisible: true,
  },
  {
    id: 'chickpea-rajasthan-rabi',
    nameEnglish: 'Chickpea (Gram)',
    nameLocal: 'चना',
    imageUrl: getImage('chickpea'),
    supportedStateIds: ['rajasthan', 'madhya-pradesh', 'maharashtra'],
    suitableSeasonIds: ['rabi'],
    soilType: 'Light to Heavy Clay',
    idealTemperature: '15-25°C',
    idealRainfall: '60-100 cm',
    expectedYield: 800,
    approximateMarketPrice: 4875,
    isVisible: true,
  },
];

export const weatherAlerts: WeatherAlert[] = [
  {
    id: 'heavy-rain-warning',
    thresholdRain: 50,
    thresholdTemperatureMin: 0,
    thresholdTemperatureMax: 50,
    frostRisk: false,
    alertMessage: 'Heavy rainfall expected. Postpone irrigation and protect young seedlings.',
    recommendedActions: 'Delay irrigation, ensure proper drainage.',
    isEnabled: true,
  },
  {
    id: 'heatwave-alert',
    thresholdRain: 100,
    thresholdTemperatureMin: 0,
    thresholdTemperatureMax: 40,
    frostRisk: false,
    alertMessage: 'Heatwave conditions approaching. Ensure adequate irrigation to prevent crop stress.',
    recommendedActions: 'Increase irrigation frequency, apply mulch.',
    isEnabled: true,
  },
  {
    id: 'frost-risk-alert',
    thresholdRain: 100,
    thresholdTemperatureMin: 4,
    thresholdTemperatureMax: 50,
    frostRisk: true,
    alertMessage: 'Frost risk overnight. Protect sensitive crops.',
    recommendedActions: 'Cover crops, use sprinklers to raise temperature.',
    isEnabled: true,
  },
  {
    id: 'moderate-rain-forecast',
    thresholdRain: 20,
    thresholdTemperatureMin: 0,
    thresholdTemperatureMax: 50,
    frostRisk: false,
    alertMessage: 'Moderate rain expected. Plan pesticide spraying accordingly.',
    recommendedActions: 'Avoid spraying pesticides 24 hours before rain.',
    isEnabled: true,
  },
  {
    id: 'high-humidity-warning',
    thresholdRain: 100,
    thresholdTemperatureMin: 0,
    thresholdTemperatureMax: 50,
    frostRisk: false,
    alertMessage: 'High humidity increases risk of fungal diseases.',
    recommendedActions: 'Monitor crops for fungal infections, ensure good air circulation.',
    isEnabled: false,
  },
];

export const farmingTips: FarmingTip[] = [
  {
    id: 'soil-testing-tip',
    tipText: 'Start the season right! Test your soil to understand nutrient needs and pH levels for better crop performance.',
    language: 'en',
    scheduledDate: new Date().toISOString(),
    isEnabled: true,
  },
  {
    id: 'crop-rotation-tip',
    tipText: 'Practice crop rotation to improve soil health, reduce pests, and increase yields. Avoid planting the same family of crops in the same field year after year.',
    language: 'en',
    scheduledDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    isEnabled: true,
  },
  {
    id: 'water-conservation-tip',
    tipText: 'Use drip irrigation or sprinklers to conserve water and deliver it directly to the crop roots, minimizing evaporation.',
    language: 'en',
    scheduledDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    isEnabled: true,
  },
  {
    id: 'ipm-tip',
    tipText: 'Adopt Integrated Pest Management (IPM). Use beneficial insects, traps, and resistant varieties before resorting to chemical pesticides.',
    language: 'en',
    scheduledDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    isEnabled: true,
  },
  {
    id: 'harvesting-tip',
    tipText: 'Harvest your crops at the right time to ensure maximum quality and market value. Check for visual cues of readiness.',
    language: 'en',
    scheduledDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    isEnabled: false,
  },
];

export const cropLifecycles: CropLifecycle[] = [
    {
        id: 'lc-wheat',
        cropId: 'wheat-haryana-rabi',
        sowingDateRange: 'Late October to mid-November',
        seedRate: '40-50 kg/acre',
        fertilizerBasalDose: 'DAP: 50kg, MOP: 20kg, Urea: 35kg per acre',
        fertilizerTopDressing: 'Urea: 50kg per acre after 25-30 days and at flowering',
        diseasePesticideGuide: 'For Yellow Rust, spray Propiconazole. For Aphids, use Imidacloprid.',
        irrigationSchedule: 'Critical stages: Crown Root Initiation, Tillering, Flowering, and Grain Filling. About 5-6 irrigations needed.',
        harvestingWindow: 'Late March to April',
        harvestingReadinessSigns: 'Golden yellow stalks, hard and dry grains.'
    },
    {
        id: 'lc-rice',
        cropId: 'rice-westbengal-kharif',
        sowingDateRange: 'June to July for transplanting',
        seedRate: '6-8 kg/acre for transplanting',
        fertilizerBasalDose: 'SSP: 75kg, Urea: 30kg, MOP: 25kg per acre',
        fertilizerTopDressing: 'Urea: 35kg per acre in two splits, at tillering and panicle initiation',
        diseasePesticideGuide: 'For Blast, use Tricyclazole. For Stem Borer, apply Fipronil granules.',
        irrigationSchedule: 'Maintain 2-5 cm of standing water for most of the growth period. Stop irrigation 15 days before harvest.',
        harvestingWindow: 'October to December',
        harvestingReadinessSigns: '80-85% of grains on the panicle are straw-colored.'
    },
    {
        id: 'lc-maize',
        cropId: 'maize-karnataka-kharif',
        sowingDateRange: 'June to July',
        seedRate: '8-10 kg/acre',
        fertilizerBasalDose: 'DAP: 50kg, MOP: 30kg per acre at sowing',
        fertilizerTopDressing: 'Urea: 50-60kg per acre at knee-high stage and another 50-60kg at tasseling.',
        diseasePesticideGuide: 'For Fall Armyworm, use Emamectin Benzoate. For Leaf Blight, Mancozeb spray is effective.',
        irrigationSchedule: 'Requires irrigation at critical stages like tasseling and silking if there is a dry spell.',
        harvestingWindow: 'September to October',
        harvestingReadinessSigns: 'Husk turns brownish, and grains are hard and dry.'
    },
    {
        id: 'lc-sugarcane',
        cropId: 'sugarcane-maharashtra-annual',
        sowingDateRange: 'October-November (pre-seasonal) or January-February (suru)',
        seedRate: '30,000-40,000 setts (stem cuttings) per acre',
        fertilizerBasalDose: 'Heavy dose of Farm Yard Manure. Chemical: 100kg Urea, 200kg SSP, 60kg MOP per acre.',
        fertilizerTopDressing: 'Urea in multiple splits at 45, 90, and 120 days after planting.',
        diseasePesticideGuide: 'For Red Rot, use disease-free setts. For Early Shoot Borer, apply Chlorantraniliprole.',
        irrigationSchedule: 'Frequent irrigation required. Use furrow irrigation method. Water every 7-10 days in summer.',
        harvestingWindow: '12-18 months after planting, depending on variety',
        harvestingReadinessSigns: 'Leaves turn yellow and wither. Canes produce a metallic sound when tapped.'
    },
    {
        id: 'lc-cotton',
        cropId: 'cotton-gujarat-kharif',
        sowingDateRange: 'Late May to June',
        seedRate: '1-2 kg/acre for hybrid seeds',
        fertilizerBasalDose: 'Full dose of Phosphorus and Potash, and 1/3 of Nitrogen at sowing.',
        fertilizerTopDressing: 'Remaining Nitrogen in two splits, at squaring and flowering stages.',
        diseasePesticideGuide: 'For Pink Bollworm, use pheromone traps and timely sprays of specific insecticides. For Whitefly, use Acetamiprid.',
        irrigationSchedule: 'Irrigate at flowering and boll development stages. Avoid water stress.',
        harvestingWindow: 'October to January, in multiple pickings',
        harvestingReadinessSigns: 'Bolls are fully mature and have begun to crack open naturally.'
    },
    {
        id: 'lc-mustard',
        cropId: 'mustard-rajasthan-rabi',
        sowingDateRange: 'Late September to October',
        seedRate: '1.5-2 kg/acre',
        fertilizerBasalDose: '25 kg DAP per acre',
        fertilizerTopDressing: 'Urea: 25 kg per acre after 30-35 days',
        diseasePesticideGuide: 'For Aphids, spray Imidacloprid. For White Rust, use Mancozeb.',
        irrigationSchedule: 'One irrigation at flowering stage is crucial if winter rains fail.',
        harvestingWindow: 'February to March',
        harvestingReadinessSigns: 'Pods turn yellow and seeds become hard.'
    },
    {
        id: 'lc-potato',
        cropId: 'potato-uttarpradesh-rabi',
        sowingDateRange: 'October to November',
        seedRate: '600-800 kg/acre of certified seed tubers',
        fertilizerBasalDose: 'FYM: 10 tons/acre. N:P:K at 50:30:50 kg/acre.',
        fertilizerTopDressing: '50 kg Nitrogen/acre at earthing up (25-30 days after planting).',
        diseasePesticideGuide: 'For Late Blight, spray Mancozeb or Chlorothalonil. For Potato Tuber Moth, use pheromone traps.',
        irrigationSchedule: 'Frequent light irrigations are needed. Maintain soil moisture. Critical stages are stolon formation and tuber development.',
        harvestingWindow: 'January to March',
        harvestingReadinessSigns: 'Haulms (stems) start to yellow and dry up.'
    },
    {
        id: 'lc-soybean',
        cropId: 'soybean-maharashtra-kharif',
        sowingDateRange: 'Late June to early July',
        seedRate: '25-30 kg/acre',
        fertilizerBasalDose: '20 kg N, 60-80 kg P2O5, 20 kg K2O, and 20 kg Sulphur per acre',
        fertilizerTopDressing: 'No top dressing generally required as it is a legume.',
        diseasePesticideGuide: 'For Rust and Anthracnose, use Mancozeb. For Girdle Beetle, spray Triazophos.',
        irrigationSchedule: 'Critical stages are flowering and pod filling. Irrigate if there is a long dry spell.',
        harvestingWindow: 'October to November',
        harvestingReadinessSigns: 'Leaves turn yellow and drop, pods become dry.'
    },
    {
        id: 'lc-groundnut',
        cropId: 'groundnut-gujarat-kharif',
        sowingDateRange: 'June-July for Kharif, October-November for Rabi',
        seedRate: '40-50 kg kernels/acre',
        fertilizerBasalDose: 'Apply 10 tons of FYM. 10 kg N, 20 kg P2O5 per acre.',
        fertilizerTopDressing: 'Apply Gypsum at 200 kg/acre during flowering.',
        diseasePesticideGuide: 'For Tikka leaf spot, spray Carbendazim or Mancozeb. For aphids, use Imidacloprid.',
        irrigationSchedule: 'Irrigation is crucial at pegging, flowering, and pod development stages.',
        harvestingWindow: 'October-November for Kharif, February-March for Rabi',
        harvestingReadinessSigns: 'Tops of plants yellow and wither. Pods are fully developed.'
    },
    {
        id: 'lc-chickpea',
        cropId: 'chickpea-rajasthan-rabi',
        sowingDateRange: 'Late October to first week of November',
        seedRate: '30-40 kg/acre for Desi type',
        fertilizerBasalDose: '8 kg N and 16 kg P2O5 per acre.',
        fertilizerTopDressing: 'Not required as it is a pulse crop.',
        diseasePesticideGuide: 'For Wilt, use resistant varieties. For Pod Borer, spray Emamectin Benzoate.',
        irrigationSchedule: 'One irrigation at pre-flowering and one at pod development stage if needed.',
        harvestingWindow: 'February to March',
        harvestingReadinessSigns: 'Leaves turn reddish-brown and start shedding.'
    }
];
